# Generated by Django 5.0.4 on 2024-04-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('name_direccion', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('detalles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id_camara', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_camara', models.CharField(max_length=255)),
                ('url_camara', models.CharField(max_length=255)),
                ('estado_camara', models.CharField(max_length=255)),
                ('frame_rate', models.CharField(max_length=255)),
                ('resolucion_camara', models.CharField(max_length=255)),
                ('notas', models.CharField(max_length=255)),
                ('id_direccion_camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camaras.direccion')),
            ],
        ),
    ]
