# Generated by Django 5.0.4 on 2024-04-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='name_direccion',
            new_name='nombre_direccion',
        ),
    ]
