# Generated by Django 4.2.7 on 2024-07-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0002_rename_name_direccion_direccion_nombre_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='id_direccion_camara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camaras.direccion'),
        ),
    ]
