# Generated by Django 5.0.4 on 2024-08-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0003_alter_camara_id_direccion_camara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='estado_camara',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='camara',
            name='frame_rate',
            field=models.CharField(max_length=25),
        ),
    ]
