# Generated by Django 5.0.4 on 2024-08-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0004_alter_camara_estado_camara_alter_camara_frame_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInfraccion',
            fields=[
                ('id_tipo_infraccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_infraccion', models.CharField(max_length=255)),
                ('cant_pagar', models.CharField(max_length=255)),
                ('detalles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_vehiculo', models.CharField(max_length=255)),
                ('detalles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id_infraccion', models.AutoField(primary_key=True, serialize=False)),
                ('id_vehiculo', models.CharField(max_length=25)),
                ('fecha_infraccion', models.DateTimeField()),
                ('velocidad_estimada', models.FloatField()),
                ('id_videoinfraccion', models.CharField(max_length=255)),
                ('frame_infraccion', models.CharField(max_length=255)),
                ('id_camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camaras.camara')),
                ('tipo_infraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camaras.tipoinfraccion')),
                ('id_tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camaras.tipovehiculo')),
            ],
        ),
    ]
