# Generated by Django 5.0.4 on 2024-09-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0005_tipoinfraccion_tipovehiculo_infraccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id_roi', models.AutoField(primary_key=True, serialize=False)),
                ('estado_roi', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_roi', models.CharField(choices=[('N', 'Normal'), ('P', 'Prohibido')], default='N', max_length=1)),
                ('coordenadas', models.CharField(max_length=50)),
                ('flujo_vehicular', models.IntegerField(blank=True, null=True)),
                ('condicion_roi', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camaras.camara')),
            ],
        ),
    ]
