# Generated by Django 5.0.4 on 2024-09-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0006_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='frame_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
