# Generated by Django 5.0.4 on 2024-09-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0007_camara_frame_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='video_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
