# Generated by Django 5.0.4 on 2024-09-21 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0008_camara_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
