# Generated by Django 5.0.4 on 2024-09-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0009_camara_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='time_video',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
