# Generated by Django 5.0.4 on 2024-09-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0010_camara_time_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='coordenadas',
            field=models.CharField(max_length=100),
        ),
    ]
