# Generated by Django 5.0.4 on 2024-10-08 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0011_alter_roi_coordenadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to='videos')),
                ('id_camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camaras.camara')),
            ],
        ),
    ]
