# Generated by Django 5.0.4 on 2024-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0012_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraccion',
            name='frame_infraccion',
        ),
        migrations.AddField(
            model_name='camara',
            name='first_frame_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infraccion',
            name='estado_infraccion',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infraccion',
            name='frame_final',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infraccion',
            name='frame_inicio',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infraccion',
            name='notas',
            field=models.CharField(default='Vacio', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infraccion',
            name='revision_infraccion',
            field=models.CharField(default='No Revisado', max_length=25),
            preserve_default=False,
        ),
    ]
