# Generated by Django 5.0.4 on 2024-10-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0014_camara_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='google_maps_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
