# Generated by Django 5.0.4 on 2024-10-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0015_direccion_google_maps_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoinfraccion',
            name='cant_pagar',
        ),
    ]
