# Generated by Django 5.0.4 on 2024-10-15 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0016_remove_tipoinfraccion_cant_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='threshold_helmet',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AddField(
            model_name='camara',
            name='threshold_license_plate',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AddField(
            model_name='camara',
            name='threshold_vehicle',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.99)]),
        ),
    ]
