# Generated by Django 5.0.4 on 2024-10-15 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0017_camara_threshold_helmet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='threshold_helmet',
            field=models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='camara',
            name='threshold_license_plate',
            field=models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='camara',
            name='threshold_vehicle',
            field=models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.99)]),
        ),
    ]
