# Generated by Django 5.0.4 on 2024-10-15 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0018_alter_camara_threshold_helmet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Umbrales',
            fields=[
                ('id_umbral', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_umbral', models.CharField(max_length=255)),
                ('valor_umbral', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(0.99)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='camara',
            name='threshold_helmet',
            field=models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='camara',
            name='threshold_license_plate',
            field=models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='camara',
            name='threshold_vehicle',
            field=models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(0.99)]),
        ),
    ]
