# Generated by Django 5.0.4 on 2024-10-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0019_umbrales_alter_camara_threshold_helmet_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Umbrales',
            new_name='Umbral',
        ),
    ]
