# Generated by Django 5.0.4 on 2024-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0020_rename_umbrales_umbral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='tipo_roi',
            field=models.CharField(choices=[('N', 'Normal'), ('P', 'Prohibido'), ('S', 'Semáforo')], default='N', max_length=1),
        ),
    ]
