# Generated by Django 5.0.4 on 2024-11-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0021_alter_roi_tipo_roi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraccion',
            name='velocidad_estimada',
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='frame_final',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='frame_inicio',
            field=models.IntegerField(max_length=25),
        ),
    ]
