# Generated by Django 5.0.4 on 2024-11-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0022_remove_infraccion_velocidad_estimada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='frame_final',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='frame_inicio',
            field=models.IntegerField(),
        ),
    ]
