# Generated by Django 5.0.4 on 2024-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0023_alter_infraccion_frame_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccion',
            name='vehicle_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
