# Generated by Django 5.0.4 on 2024-11-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0024_infraccion_vehicle_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='revision_infraccion',
            field=models.CharField(max_length=100),
        ),
    ]
