# Generated by Django 5.0.4 on 2024-11-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0025_alter_infraccion_revision_infraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='google_embeded_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
